name: Self-hosted Java CI Demo

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build and run the MBT/PBT demo with Maven
        run: mvn test
